# Spring Boot App
version: '3.3'
services:
  # Postgresql 11 DB
  postgres-db:
    container_name: "postgres-db"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
    image: postgres:11-alpine
    env_file: .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    network_mode: host
  # Spring boot app
  app:
    container_name: "odm-dpexperience-service"
    depends_on:
      - postgres-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: "docker"
        SPRING_LOCAL_PORT: "${SPRING_LOCAL_PORT}"
        APP_NAME: "odm-dpexperience-service"
        JAVA_OPTS: ""
        DATABASE_URL:  "jdbc:postgresql://localhost:5432/odmpdb" #:${DATABASE_PORT}/${DATABASE_NAME}/"
        DATABASE_USERNAME: "${DATABASE_USERNAME}"
        DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
        FLYWAY_SCHEMA: "flyway"
        FLYWAY_SCRIPTS_DIR: "postgres"
        H2_CONSOLE_ENABLED: "false"
        H2_CONSOLE_PATH: "h2-console"
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"