# Postgres 11 Docker image
services:
  postgres:
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: db
    image: postgres:11-alpine
    ports:
      - published: 5432
        target: 5432
    network_mode: "host"
    #volumes:
    #  - postgres:/var/lib/postgresql/data:rw
version: '3.3'
volumes:
  postgres: {}